### ISSUE TITLE
Tread Material Issue

### ISSUE THREAD

**Issue by MarcProux** [BoredEngineer/UE4_Tracked_Vehicles#1]
This project is awesome, you make an awesome work maybe i've an issue..

When i launch the game in editor i've a Runtime Error:

```
Blueprint Runtime Error: Accessed None trying to read property TreadMaterialRight from function: 'AnimateTreadsMaterial' from node: Set Scalar Parameter Value in graph: AnimateTreadsMaterial in object: A_TrackedVehicle with description: Accessed None trying to read property TreadMaterialRight
Blueprint Runtime Error: Accessed None trying to read property TreadMaterialLeft from function: 'AnimateTreadsMaterial' from node: Set Scalar Parameter Value in graph: AnimateTreadsMaterial in object: A_TrackedVehicle with description: Accessed None trying to read property TreadMaterialLeft
```

I put a material into TreadsR and TreadsL but already the same issue. Can you help me to understand ?

**Comment by BoredEngineer** [comment]
Weird. Which UE4 version are you using?

**Comment by MarcProux** [comment]
I use the latest stable version, 4.12.4

**Comment by BoredEngineer** [comment]
Have you done any changes to the project?

References to materials are set in CreateMaterialsForSimpleTracks function in constructor graph. Then materials are applied to InstancedStaticMeshComponent tracks, which is kind of wrong as you might have your own materials there.
you can disable it like this:
https://www.dropbox.com/s/12odhoc69irlrh9/ConstructorTrackMaterials.JPG?dl=0
and then disable a function which throws errors:
https://www.dropbox.com/s/streq11fgocp7dn/ConstructorTrackMaterials_eventgraph.JPG?dl=0

I can do this changes on my side, but I would first convert it into 4.12 and see if something else is going wrong.

Overall I would advise to use tracked vehicle from MMT_Content as it works properly with varied FPS.

**Comment by BoredEngineer** [comment]
I'll make a 4.9 fork then and upgrade master to 4.12

**Comment by MarcProux** [comment]
I fix this issue, and i will try to use MMT_Content.

Thanks for your help

**Comment by OurGhostsOfWar** [comment]
Hello, first of all I have to say this is a great project and thanks to BoredEngineer for making it available to the community!

I only have one issue with it so far that I could not fix on my own. All of the vehicles, both the ones provided in the level as well as my own experience a significant jittering. Any idea what might cause this and how to prevent it? 

I'm running it on 4.12.5
Thank you!
